//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sia.ControlAlmacenDigital.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilDireccion
    {
        public string UsuarioId { get; set; }
        public string CodigoPostal { get; set; }
        public string Calle { get; set; }
        public string NumeroExterior { get; set; }
        public string NumeroInterior { get; set; }
        public string Colonia { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string UsuarioModificadorId { get; set; }
    
        public virtual Perfil Perfil { get; set; }
    }
}
