//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sia.ControlAlmacenDigital.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio
    {
        public int PrecioId { get; set; }
        public int ProductoId { get; set; }
        public double Precio1 { get; set; }
        public Nullable<double> Precio2 { get; set; }
        public Nullable<double> Precio3 { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> ayo { get; set; }
        public Nullable<int> Emitio { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
