//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sia.ControlAlmacenDigital.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Precio = new HashSet<Precio>();
            this.ProductoExistencia = new HashSet<ProductoExistencia>();
            this.ProductoFotografia = new HashSet<ProductoFotografia>();
        }
    
        public int ProductoId { get; set; }
        public int CategoriaId { get; set; }
        public string Codigo { get; set; }
        public string CodigoBarra { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Pieza { get; set; }
        public string Descripcion { get; set; }
        public string Color { get; set; }
        public string Capacidad { get; set; }
        public string Material { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Medida { get; set; }
        public Nullable<bool> EsPrincipal { get; set; }
        public string CodigoPrincipal { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio> Precio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoExistencia> ProductoExistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoFotografia> ProductoFotografia { get; set; }
    }
}
