//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sia.ControlAlmacenDigital.WebApi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sia.ControlAlmacenDigital.WebApi.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error en el sistema..
        /// </summary>
        internal static string ErrorAgregar {
            get {
                return ResourceManager.GetString("ErrorAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al guardar la imagen..
        /// </summary>
        internal static string ErrorAgregarFoto {
            get {
                return ResourceManager.GetString("ErrorAgregarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error en el sistema..
        /// </summary>
        internal static string ErrorEditar {
            get {
                return ResourceManager.GetString("ErrorEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al eliminar el registro..
        /// </summary>
        internal static string ErrorEliminar {
            get {
                return ResourceManager.GetString("ErrorEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatos soportados .jpg,.gif,.png..
        /// </summary>
        internal static string ErrorFormatoFoto {
            get {
                return ResourceManager.GetString("ErrorFormatoFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso máximo de la imagen 1 mb..
        /// </summary>
        internal static string ErrorPesoMaxFoto {
            get {
                return ResourceManager.GetString("ErrorPesoMaxFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro agregado..
        /// </summary>
        internal static string ExitoAgregar {
            get {
                return ResourceManager.GetString("ExitoAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen guardada correctamente..
        /// </summary>
        internal static string ExitoAgregarFoto {
            get {
                return ResourceManager.GetString("ExitoAgregarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro actualizado..
        /// </summary>
        internal static string ExitoEditar {
            get {
                return ResourceManager.GetString("ExitoEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro eliminado..
        /// </summary>
        internal static string ExitoEliminar {
            get {
                return ResourceManager.GetString("ExitoEliminar", resourceCulture);
            }
        }
    }
}
